# Generated by Django 4.2.2 on 2023-07-08 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bfapp", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CustomUser",
        ),
    ]
