# Generated by Django 4.2.2 on 2023-07-04 22:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("bfapp", "0004_user_auth_token_delete_accesstoken"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="auth_token",
        ),
        migrations.CreateModel(
            name="AccessToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("access_token", models.CharField(max_length=255)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="bfapp.user"
                    ),
                ),
            ],
        ),
    ]
