# Generated by Django 4.2.2 on 2023-07-05 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bfapp", "0005_remove_user_auth_token_accesstoken"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="accesstoken",
            name="user",
        ),
        migrations.AddField(
            model_name="accesstoken",
            name="username",
            field=models.CharField(default="--", max_length=64),
        ),
        migrations.AddField(
            model_name="accesstoken",
            name="userpk",
            field=models.IntegerField(default=0),
        ),
    ]
