# Generated by Django 4.2.2 on 2023-07-06 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("bfapp", "0006_remove_accesstoken_user_accesstoken_username_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="accesstoken",
            name="username",
        ),
        migrations.RemoveField(
            model_name="accesstoken",
            name="userpk",
        ),
        migrations.AddField(
            model_name="accesstoken",
            name="user",
            field=models.OneToOneField(
                default=1, on_delete=django.db.models.deletion.CASCADE, to="bfapp.user"
            ),
            preserve_default=False,
        ),
    ]
